name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 0'


jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.PCCIBOT_PAT_REPO_PUBLIC_REPO }}
    env:
      LOG_LEVEL: 'debug'
